[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-plus -ra -v"
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL"
testpaths = [
    "cblearn",
]
markers = [
    "sklearn: mark tests for sklearn compatibility.",
]
