# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.platform }} ${{ matrix.python-version }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]
        include:
          - platform: ubuntu-latest
            python-version: 3.8
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
    - name: Install package with dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[r_wrapper,tests,docs]
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics
    - name: Test with pytest and measure coverage
      run: |
        pytest cblearn --cov=cblearn --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
    - name: Build the documentation
      run: |
        python setup.py build_sphinx